version: "3.3"
services:
  lavalink:
    image: ghcr.io/stefanlobbenmeier/lavalink:latest
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
  lavamusic:
    image: ghcr.io/stefanlobbenmeier/lavamusic:dockerfile
    volumes:
      - ./.env:/opt/lavamusic/.env
    links:
      - mongo
      - lavalink
  mongo:
    image: webhippie/mongodb:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
