version: "3.3"
services:
  lavalink:
    image: fredboat/lavalink:master
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
  lavamusic:
    image: ghcr.io/brblacky/lavamusic:latest
    volumes:
      - ./.env:/opt/lavamusic/.env
    links:
      - mongo
      - lavalink
    depends_on:
      - lavalink
      - mongo
  mongo:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
