version: "3.3"
services:
  lavalink:
    image: fredboat/lavalink:master
    volumes:
      - application.yml:/opt/Lavalink/application.yml
  lavamusic:
    image: ghcr.io/stefanlobbenmeier/lavamusic:dockerfile
    volumes:
      - .env:/usr/src/lavalink/.env
    links:
      - mongo
      - lavalink
  mongo:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
